source 'https://rubygems.org'

gem 'bundler'

gem 'sqlite3'
# require "sequel"

# gem 'capybara'
# gem 'poltergeist'
# gem 'nokogiri'

# gem 'farm_ruby', :git => 'https://github.com/jessethebuilder/farm_ruby'
gem 'farm_ruby', :path => 'C:\Users\Bucky\Desktop\jesseweb\farm_ruby'

# gem 'farm_scrape', :git => 'https://github.com/jessethebuilder/farm_scrape'
gem 'farm_scrape', :path => 'C:\Users\Bucky\Desktop\jesseweb\farm_scrape'
